package com.velocityorm.core.dialect;

import com.velocityorm.core.metadata.ColumnMeta;
import com.velocityorm.core.metadata.EntityMeta;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class PostgresDialect implements Dialect {

    @Override
    public String getName() {
        return "PostgreSQL";
    }

    private String getSqlType(ColumnMeta col) {
        Class<?> type = col.getFieldType();
        if (col.isEncrypted()) {
            return "VARCHAR(1000)"; // Encryption needs extra space for ciphertext/hex
        }
        if (type == String.class) {
            return "VARCHAR(" + col.getLength() + ")";
        } else if (type == Long.class || type == long.class) {
            return "BIGINT";
        } else if (type == Integer.class || type == int.class) {
            return "INTEGER";
        } else if (type == Double.class || type == double.class) {
            return "DOUBLE PRECISION";
        } else if (type == Boolean.class || type == boolean.class) {
            return "BOOLEAN";
        } else if (type == java.math.BigDecimal.class) {
            return "NUMERIC";
        } else if (type == java.time.LocalDateTime.class || type == java.util.Date.class) {
            return "TIMESTAMP";
        }
        return "VARCHAR(255)";
    }

    private String getProcedureParamType(ColumnMeta col) {
        Class<?> type = col.getFieldType();
        if (type == String.class) {
            return "varchar";
        } else if (type == Long.class || type == long.class) {
            return "bigint";
        } else if (type == Integer.class || type == int.class) {
            return "integer";
        } else if (type == Double.class || type == double.class) {
            return "double precision";
        } else if (type == Boolean.class || type == boolean.class) {
            return "boolean";
        } else if (type == java.math.BigDecimal.class) {
            return "numeric";
        } else if (type == java.time.LocalDateTime.class || type == java.util.Date.class) {
            return "timestamp";
        }
        return "varchar";
    }

    @Override
    public String generateCreateTable(EntityMeta<?, ?> meta) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE IF NOT EXISTS ").append(quoteIdentifier(meta.getTableName())).append(" (");
        
        List<String> colDefs = new ArrayList<>();
        for (ColumnMeta col : meta.getColumns()) {
            StringBuilder colDef = new StringBuilder();
            colDef.append(quoteIdentifier(col.getColumnName())).append(" ").append(getSqlType(col));
            if (col.isId()) {
                colDef.append(" PRIMARY KEY");
                if (meta.isIdGenerated()) {
                    colDef.append(" GENERATED BY DEFAULT AS IDENTITY");
                }
            } else {
                if (!col.isNullable()) {
                    colDef.append(" NOT NULL");
                }
                if (col.isUnique()) {
                    colDef.append(" UNIQUE");
                }
            }
            colDefs.add(colDef.toString());
        }
        sb.append(String.join(", ", colDefs));
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String generateCreateIndex(String tableName, String columnName, String indexName, boolean unique) {
        return "CREATE " + (unique ? "UNIQUE " : "") + "INDEX IF NOT EXISTS " + 
               quoteIdentifier(indexName) + " ON " + quoteIdentifier(tableName) + " (" + quoteIdentifier(columnName) + ")";
    }

    @Override
    public List<String> generateInsertProcedure(EntityMeta<?, ?> meta) {
        String procName = "sp_" + meta.getTableName() + "_insert";
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE PROCEDURE ").append(procName).append("(");
        
        List<String> params = new ArrayList<>();
        // ID parameter
        if (meta.isIdGenerated()) {
            params.add("INOUT p_" + meta.getIdColumnName() + " " + getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName())));
        } else {
            params.add("IN p_" + meta.getIdColumnName() + " " + getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName())));
        }
        
        // Other columns
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            params.add("IN p_" + col.getColumnName() + " " + getProcedureParamType(col));
        }
        
        sb.append(String.join(", ", params)).append(") AS $$\nBEGIN\n");
        sb.append("    INSERT INTO ").append(quoteIdentifier(meta.getTableName())).append(" (");
        
        List<String> cols = new ArrayList<>();
        List<String> vals = new ArrayList<>();
        if (!meta.isIdGenerated()) {
            cols.add(quoteIdentifier(meta.getIdColumnName()));
            vals.add("p_" + meta.getIdColumnName());
        }
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            cols.add(quoteIdentifier(col.getColumnName()));
            vals.add("p_" + col.getColumnName());
        }
        
        sb.append(String.join(", ", cols)).append(") VALUES (");
        sb.append(String.join(", ", vals)).append(")");
        
        if (meta.isIdGenerated()) {
            sb.append(" RETURNING ").append(quoteIdentifier(meta.getIdColumnName())).append(" INTO p_").append(meta.getIdColumnName());
        }
        sb.append(";\nEND;\n$$ LANGUAGE plpgsql;");
        
        return List.of(sb.toString());
    }

    @Override
    public List<String> generateUpdateProcedure(EntityMeta<?, ?> meta) {
        String procName = "sp_" + meta.getTableName() + "_update";
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE PROCEDURE ").append(procName).append("(");
        
        List<String> params = new ArrayList<>();
        params.add("IN p_" + meta.getIdColumnName() + " " + getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName())));
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            params.add("IN p_" + col.getColumnName() + " " + getProcedureParamType(col));
        }
        
        sb.append(String.join(", ", params)).append(") AS $$\nBEGIN\n");
        sb.append("    UPDATE ").append(quoteIdentifier(meta.getTableName())).append(" SET ");
        
        List<String> updates = new ArrayList<>();
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            updates.add(quoteIdentifier(col.getColumnName()) + " = p_" + col.getColumnName());
        }
        sb.append(String.join(", ", updates));
        sb.append(" WHERE ").append(quoteIdentifier(meta.getIdColumnName())).append(" = p_").append(meta.getIdColumnName()).append(";\nEND;\n$$ LANGUAGE plpgsql;");
        
        return List.of(sb.toString());
    }

    @Override
    public List<String> generateDeleteProcedure(EntityMeta<?, ?> meta) {
        String procName = "sp_" + meta.getTableName() + "_delete";
        String idParamType = getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName()));
        String sql = "CREATE OR REPLACE PROCEDURE " + procName + "(IN p_" + meta.getIdColumnName() + " " + idParamType + ") AS $$\n" +
                     "BEGIN\n" +
                     "    DELETE FROM " + quoteIdentifier(meta.getTableName()) + " WHERE " + quoteIdentifier(meta.getIdColumnName()) + " = p_" + meta.getIdColumnName() + ";\n" +
                     "END;\n" +
                     "$$ LANGUAGE plpgsql;";
        return List.of(sql);
    }

    @Override
    public List<String> generateGetProcedure(EntityMeta<?, ?> meta) {
        String procName = "sp_" + meta.getTableName() + "_get";
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE PROCEDURE ").append(procName).append("(");
        sb.append("INOUT p_").append(meta.getIdColumnName()).append(" ").append(getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName())));
        
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            sb.append(", INOUT p_").append(col.getColumnName()).append(" ").append(getProcedureParamType(col));
        }
        
        sb.append(") AS $$\nBEGIN\n");
        sb.append("    SELECT ");
        
        List<String> selectCols = meta.getColumns().stream()
                .filter(c -> !c.isId())
                .map(c -> quoteIdentifier(c.getColumnName()))
                .collect(Collectors.toList());
        List<String> intoVars = meta.getColumns().stream()
                .filter(c -> !c.isId())
                .map(c -> "p_" + c.getColumnName())
                .collect(Collectors.toList());
        
        sb.append(String.join(", ", selectCols));
        sb.append(" INTO ");
        sb.append(String.join(", ", intoVars));
        sb.append(" FROM ").append(quoteIdentifier(meta.getTableName()));
        sb.append(" WHERE ").append(quoteIdentifier(meta.getIdColumnName())).append(" = p_").append(meta.getIdColumnName()).append(";\n");
        sb.append("    IF NOT FOUND THEN\n");
        sb.append("        p_").append(meta.getIdColumnName()).append(" := NULL;\n");
        sb.append("    END IF;\n");
        sb.append("END;\n$$ LANGUAGE plpgsql;");
        
        return List.of(sb.toString());
    }

    @Override
    public List<String> generateBatchInsertProcedure(EntityMeta<?, ?> meta) {
        String procName = "sp_" + meta.getTableName() + "_batch_insert";
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE PROCEDURE ").append(procName).append("(");
        
        List<String> params = new ArrayList<>();
        if (!meta.isIdGenerated()) {
            params.add("IN p_" + meta.getIdColumnName() + "s " + getProcedureParamType(meta.getColumnByFieldName(meta.getIdFieldName())) + "[]");
        }
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            params.add("IN p_" + col.getColumnName() + "s " + getProcedureParamType(col) + "[]");
        }
        
        sb.append(String.join(", ", params)).append(") AS $$\nBEGIN\n");
        sb.append("    INSERT INTO ").append(quoteIdentifier(meta.getTableName())).append(" (");
        
        List<String> cols = new ArrayList<>();
        List<String> unnestArgs = new ArrayList<>();
        if (!meta.isIdGenerated()) {
            cols.add(quoteIdentifier(meta.getIdColumnName()));
            unnestArgs.add("p_" + meta.getIdColumnName() + "s");
        }
        for (ColumnMeta col : meta.getColumns()) {
            if (col.isId()) continue;
            cols.add(quoteIdentifier(col.getColumnName()));
            unnestArgs.add("p_" + col.getColumnName() + "s");
        }
        
        sb.append(String.join(", ", cols)).append(") ");
        sb.append("SELECT * FROM unnest(").append(String.join(", ", unnestArgs)).append(");\nEND;\n$$ LANGUAGE plpgsql;");
        
        return List.of(sb.toString());
    }

    @Override
    public String getInsertCallStatement(EntityMeta<?, ?> meta) {
        int paramCount = meta.getColumns().size();
        return "CALL sp_" + meta.getTableName() + "_insert(" + getPlaceholders(paramCount) + ")";
    }

    @Override
    public String getUpdateCallStatement(EntityMeta<?, ?> meta) {
        int paramCount = meta.getColumns().size();
        return "CALL sp_" + meta.getTableName() + "_update(" + getPlaceholders(paramCount) + ")";
    }

    @Override
    public String getDeleteCallStatement(EntityMeta<?, ?> meta) {
        return "CALL sp_" + meta.getTableName() + "_delete(?)";
    }

    @Override
    public String getGetCallStatement(EntityMeta<?, ?> meta) {
        int paramCount = meta.getColumns().size();
        return "CALL sp_" + meta.getTableName() + "_get(" + getPlaceholders(paramCount) + ")";
    }

    @Override
    public String getBatchInsertCallStatement(EntityMeta<?, ?> meta) {
        int paramCount = meta.isIdGenerated() ? meta.getColumns().size() - 1 : meta.getColumns().size();
        return "CALL sp_" + meta.getTableName() + "_batch_insert(" + getPlaceholders(paramCount) + ")";
    }

    @Override
    public String paginate(String sql, int limit, int offset) {
        return sql + " LIMIT " + limit + " OFFSET " + offset;
    }

    @Override
    public String quoteIdentifier(String name) {
        return "\"" + name + "\"";
    }

    @Override
    public boolean tableExists(Connection conn, String tableName) throws SQLException {
        try (var rs = conn.getMetaData().getTables(null, null, null, new String[]{"TABLE"})) {
            while (rs.next()) {
                if (tableName.equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    @Override
    public boolean procedureExists(Connection conn, String procedureName) throws SQLException {
        try (var rs = conn.getMetaData().getProcedures(null, null, null)) {
            while (rs.next()) {
                if (procedureName.equalsIgnoreCase(rs.getString("PROCEDURE_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }
}
